common:
  data_root: data/MouseSIS
  iou_threshold: 0.1
  split: test
  sequence_ids: [1, 7, 10, 16, 22, 26, 28, 32]

gray_detector:
  yolo_path: /data/hj_data/CVPR/Mouse/MouseSIS-0.1.0/runs_frame_yolo12_e80/detect/mice_yolo_frame/weights/last.pt #./models/yolo_frame.pt

e2vid_detector:
  yolo_path: /data/hj_data/CVPR/Mouse/MouseSIS-0.1.0/runs/detect/mice_yolo_e2vid/weights/last.pt #./models/yolo_e2vid.pt

tracker:
  max_age: 1
  min_hits: 3
  iou_threshold: 0.3

output_dir: ./output/
